Repository trace4cats/trace4cats-http4s, pull requests merged in 2021-07, with the labels that each got.

#6 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#9 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#10 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#11 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#12 Add Scala 3 build
  .github/workflows/ci.yml
  ci-release.sbt
  modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/ClientTracer.scala
  modules/http4s-client/src/test/scala/io/janstenpickle/trace4cats/http4s/client/ClientCtxSyntaxSpec.scala
  modules/http4s-client/src/test/scala/io/janstenpickle/trace4cats/http4s/client/ClientSyntaxSpec.scala
  modules/http4s-client/src/test/scala/io/janstenpickle/trace4cats/http4s/client/Instances.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/CommonInstances.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/Http4sHeadersConverterSpec.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/RunIOToId.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/RunKleisliWithEmptyTraceContext.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/RunKleisliWithNoopSpan.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/BaseServerTracerSpec.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/Instances.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/ResourceKleisliServerCtxSyntaxSpec.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/ResourceKleisliServerSyntaxSpec.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/ServerCtxSyntaxSpec.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/ServerSyntaxSpec.scala
  project/Dependencies.scala
Labels: enhancement
